### PR TITLE
Update athletewidget.cpp-Add Skill to txt/csv import

### PR DESCRIPTION
**Pull request by kalactin**
[https://github.com/kalactin/Xkoranate-CE-1/blob/patch-1/src/signuplisteditor/athletewidget.cpp](url)

### CODE REVIEW

**Comment by blackmage37** [comment]
@kalactin did you test the build? i tried today and text import no longer works.

**Comment by kalactin** [comment]
Unfortunately, I am not able to test it, due to my computers inability to run 32 bit apps.

**Comment by blackmage37** [comment]
ok well i cant approve this PR until we have confirmation that it works, im afraid

**Comment by kalactin** [comment]
Did you compile the entire github version? Or just the files changed? I think someone said that they couldn’t get the github version to compile, so we might need to find out why spit won’t compile.

**Comment by blackmage37** [comment]
@kalactin 

Untested changes should never be committed to the master branch. Really, the dev branch (or a new branch specifically for whatever bug you're working on) should be the first place you make changes. Then merge to test for testing. Then merge to master. This prevents us from merging faults into the master branch code, which could break the entire program when someone downloads it in the future.

I would recommend closing submitting a new pull request to the test branch, where the changes can be tested and confirmed. Once confirmed, we can merge them into the master branch. The same applies to #15

**Pull request closed without merging**
